name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: 🤖 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          cache-dependency-path: '**/package.json'

      - name: install
        shell: bash
        run: npm i

      - name: 🧪 Unit Tests
        shell: bash
        run: npm run test

